name: test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: go test
        run: go run -ldflags "-X main.branch=${{ github.ref_name }} -X main.commit=${{ github.sha }}" ./ci/cmd/main.go